server:
  port: 5432
  error:
    include-message: always
spring:
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  datasource:
    url: ec2-34-197-84-74.compute-1.amazonaws.com:5432/d2s516si419d71?socketTimeout=3
    username: nupmuzcuczkybf
    password: e30a0e936a37f57ff6aa06a8bb2ef47d976f5446755f7a94364387dc38eb2c63
    driverClassName: org.postgresql.Driver


